### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kungfooman** [vjeux/jspp#2]
Hi, this is a very interesting project and I would like to put it into one of my repos for testing. But until I know the license, I won't add it. Could you assign some license like MIT please? 

Thanks alot for all the work you put into this.

Also, I don't know if you know it, this is quite interesting aswell: http://sasq64.github.io/cpp-javascript.html

**Comment by vjeux** [comment]
I just added a MIT license :)

https://github.com/vjeux/jspp/blob/master/LICENSE
